### ISSUE TITLE
淘宝和支付宝网站支持的不好，抛出异常

### ISSUE THREAD

**Issue by GangLiCN** [kangvcar/InfoSpider#31]
## Bug Report

**Description**: [Description of the issue]
Traceback (most recent call last):
  File "main.py", line 520, in OnClick
    t = TaobaoSpider(cookie_list)
  File "E:\my_work_spaces\pycharm\Self_learn_projs\Crawler_projs\InfoSpider-master\./Spiders\taobao\spider.py", line 65, in __init__
    self.path = askdirectory(title='选择信息保存文件夹')
  File "G:\py37\lib\tkinter\filedialog.py", line 428, in askdirectory
    return Directory(**options).show()
  File "G:\py37\lib\tkinter\commondialog.py", line 39, in show
    w = Frame(self.master)
  File "G:\py37\lib\tkinter\__init__.py", line 2744, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "G:\py37\lib\tkinter\__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
RuntimeError: main thread is not in main loop

**Comment by kangvcar** [comment]
已修复

**Comment by kangvcar** [comment]
@GangLiCN 已修复
